// src/lib/module-checklists.ts
// Checklists detallados por módulo — tareas concretas de ejecución

export interface ChecklistItem {
  id: string
  text: string
  detail?: string
  critical?: boolean        // Tarea esencial que desbloquea lo siguiente
  tool?: string             // Herramienta asociada
  time?: string             // Tiempo estimado
  category?: string         // Agrupación dentro del checklist
}

export interface ModuleChecklist {
  moduleSlug: string
  title: string
  description: string
  items: ChecklistItem[]
  completionMessage: string
  nextAction: string
}

export const MODULE_CHECKLISTS: Record<string, ModuleChecklist> = {

  // ─────────────────────────────────────────────
  // MÓDULO 1 — MENTALIDAD Y REALIDAD
  // ─────────────────────────────────────────────
  'modulo-1-mentalidad': {
    moduleSlug: 'modulo-1-mentalidad',
    title: 'Checklist — Módulo 1',
    description: 'Completá estas tareas antes de pasar al Módulo 2. Son la base de todo lo que viene.',
    completionMessage: '¡Módulo 1 completado! Tenés tu misión clara y tu punto de partida definido. Eso ya te pone adelante del 90% de la gente.',
    nextAction: 'Empezar Módulo 2: Elige Tu Nicho',
    items: [
      {
        id: 'm1-ver-lecciones',
        text: 'Ver las 3 lecciones del Módulo 1',
        detail: 'Lección 1.1 (Historia), 1.2 (Punto de partida), 1.3 (Por qué dólares)',
        critical: true,
        time: '~45 min',
        category: 'Lecciones',
      },
      {
        id: 'm1-libertad',
        text: 'Definir tu número de libertad financiera en dólares',
        detail: 'Calculá tu gasto mensual real: renta + comida + servicios + deudas + margen. Ese es tu número, no una cifra fantasía.',
        critical: true,
        time: '15 min',
        category: 'Workbook',
      },
      {
        id: 'm1-inventario',
        text: 'Hacer el inventario honesto de tus recursos actuales',
        detail: 'Habilidad vendible, acceso a internet, horas disponibles, capital para inversión. Sin mentirte.',
        critical: true,
        time: '15 min',
        category: 'Workbook',
      },
      {
        id: 'm1-meta',
        text: 'Fijar tu meta de 90 días con fecha límite específica',
        detail: 'Un número en USD que te incomode un poco pero que sea alcanzable. Con fecha exacta (día, mes, año).',
        critical: true,
        time: '5 min',
        category: 'Workbook',
      },
      {
        id: 'm1-razon',
        text: 'Escribir tu razón en una frase',
        detail: '"Voy a construir esto porque..." — tu razón real, no la que suena bonita. La que te va a sostener cuando quieras rendirte.',
        critical: true,
        time: '10 min',
        category: 'Workbook',
      },
      {
        id: 'm1-workbook',
        text: 'Guardar el workbook del Módulo 1 completo',
        detail: 'Tiene que estar guardado, no en tu cabeza. Lo vas a necesitar cuando quieras rendirte.',
        time: '5 min',
        category: 'Workbook',
      },
      {
        id: 'm1-excusas',
        text: 'Identificar y escribir tus excusas principales',
        detail: '¿Cuáles de las 4 excusas clásicas eras o son tuyas? Sin experiencia, sin inglés, sin dinero, no es el momento. Escríbelas y después tacha cada una con su respuesta.',
        time: '10 min',
        category: 'Reflexión',
      },
      {
        id: 'm1-compromiso',
        text: 'Escribir el compromiso y compartirlo con alguien de confianza',
        detail: 'Opcional pero poderoso: decirle a alguien cercano lo que estás haciendo aumenta dramáticamente la probabilidad de que lo cumplas.',
        time: '5 min',
        category: 'Reflexión',
      },
    ],
  },

  // ─────────────────────────────────────────────
  // MÓDULO 2 — ELIGE TU NICHO
  // ─────────────────────────────────────────────
  'modulo-2-nicho': {
    moduleSlug: 'modulo-2-nicho',
    title: 'Checklist — Módulo 2',
    description: 'Definir tu cliente ideal correctamente es la decisión más importante del negocio. No pases al Módulo 3 sin completar esto.',
    completionMessage: '¡Nicho definido! Tenés un cliente ideal claro, un dolor documentado, y sabes dónde encontrarlo. Eso es el 50% de la venta.',
    nextAction: 'Empezar Módulo 3: Diseña Tu Oferta',
    items: [
      {
        id: 'm2-ver-lecciones',
        text: 'Ver las 6 lecciones del Módulo 2',
        detail: 'Cliente ideal, psicografía, 5 filtros, triángulo de experiencia, auditoría de pasado, dónde vive tu cliente',
        critical: true,
        time: '~2 horas',
        category: 'Lecciones',
      },
      {
        id: 'm2-tres-icp',
        text: 'Identificar 3 posibles clientes ideales',
        detail: 'Tres tipos diferentes de clientes a los que podrías vender. No necesitás elegir todavía, solo identificarlos.',
        critical: true,
        time: '20 min',
        category: 'Investigación',
      },
      {
        id: 'm2-filtros',
        text: 'Aplicar los 5 filtros a cada cliente ideal y calcular puntaje',
        detail: 'Dolor (1-5) + Urgencia (1-5) + Capacidad de pago (1-5) + Autoridad (1-5) + Comunidad (1-5) = puntaje sobre 25. El más alto es tu candidato.',
        critical: true,
        time: '30 min',
        category: 'Investigación',
      },
      {
        id: 'm2-elegir-icp',
        text: 'Elegir UN nicho y comprometerte por 30 días',
        detail: 'No dos. No "voy a probar varios". Uno. Si no funciona después de 30 días de trabajo real, ajustás. Pero dale la oportunidad primero.',
        critical: true,
        time: '10 min',
        category: 'Decisión',
      },
      {
        id: 'm2-psicografia',
        text: 'Documentar la psicografía completa de tu ICP',
        detail: 'Dolor principal (en sus palabras), creencias sobre el problema, qué ha intentado, si sabe que tiene el problema, resultado emocional que busca.',
        critical: true,
        time: '30 min',
        category: 'Workbook',
      },
      {
        id: 'm2-auditoria',
        text: 'Hacer la auditoría de experiencia propia',
        detail: 'Revisar tus últimos 2-3 trabajos o proyectos. ¿En qué industria tenés ventaja natural? ¿Qué problemas viste desde adentro?',
        time: '20 min',
        category: 'Reflexión',
      },
      {
        id: 'm2-google-maps',
        text: 'Buscar tu ICP en Google Maps — mínimo 20 resultados',
        detail: 'Abrir Google Maps, buscar tu tipo de negocio en 2-3 ciudades de USA. Si aparecen menos de 20 resultados, el nicho puede ser muy pequeño.',
        critical: true,
        tool: 'Google Maps',
        time: '10 min',
        category: 'Prueba de realidad',
      },
      {
        id: 'm2-linkedin',
        text: 'Buscar tu ICP en LinkedIn — confirmar que existen',
        detail: 'Buscar por título + industria + ubicación en USA. Si aparecen miles de resultados, estás bien.',
        critical: true,
        tool: 'LinkedIn',
        time: '10 min',
        category: 'Prueba de realidad',
      },
      {
        id: 'm2-instagram',
        text: 'Buscar tu ICP en Instagram por hashtags y ubicación',
        detail: 'Hashtags de la industria + geolocalización. Mirá si tienen presencia activa o abandonada.',
        time: '10 min',
        category: 'Prueba de realidad',
      },
      {
        id: 'm2-grupos-fb',
        text: 'Entrar a grupos de Facebook de tu nicho y escuchar',
        detail: 'Buscar grupos activos de tu industria. Leer qué se quejan, qué preguntan, qué soluciones buscan. No vendas todavía.',
        time: '20 min',
        category: 'Investigación',
      },
      {
        id: 'm2-icp-alcanzable',
        text: 'Confirmar que podés encontrar a tu ICP en menos de 10 minutos',
        detail: 'Prueba final: sentate, abrí una plataforma, y en 10 minutos tenés 20+ prospectos reales con nombre y datos. Si no podés, ajustá el nicho.',
        critical: true,
        time: '10 min',
        category: 'Prueba de realidad',
      },
      {
        id: 'm2-workbook',
        text: 'Completar la Ficha de Cliente Ideal en el workbook',
        detail: 'Resumen del ICP, industria, dolores, resultado deseado, urgencia, objeciones, plataformas. Guardado y completo.',
        time: '20 min',
        category: 'Workbook',
      },
    ],
  },

  // ─────────────────────────────────────────────
  // MÓDULO 3 — DISEÑA TU OFERTA
  // ─────────────────────────────────────────────
  'modulo-3-oferta': {
    moduleSlug: 'modulo-3-oferta',
    title: 'Checklist — Módulo 3',
    description: 'Al terminar esto tenés tu oferta completa lista para presentarla mañana. Sin necesitar logo ni web.',
    completionMessage: '¡Oferta lista! Tenés algo concreto que ofrecer con precio claro y valor demostrable. Eso es un negocio real.',
    nextAction: 'Empezar Módulo 4: Incorporación en USA',
    items: [
      {
        id: 'm3-ver-lecciones',
        text: 'Ver las 4 lecciones del Módulo 3',
        detail: 'Oferta no necesita ser perfecta, 4 pilares, pricing, oferta completa',
        critical: true,
        time: '~1.5 horas',
        category: 'Lecciones',
      },
      {
        id: 'm3-frase-oferta',
        text: 'Escribir tu frase de oferta usando la fórmula',
        detail: '"Yo ayudo a [quién] a lograr [qué] sin [obstáculo]." — Una sola frase. No un párrafo. Que quepa en un tweet.',
        critical: true,
        time: '20 min',
        category: 'Oferta',
      },
      {
        id: 'm3-4-pilares',
        text: 'Pasar la oferta por los 4 pilares y calificar del 1-5',
        detail: 'Resultado grande (1-5), Probabilidad percibida (1-5), Tiempo a resultados (1-5), Esfuerzo del cliente (1-5). Si alguno está bajo 3, reforzá ese punto.',
        critical: true,
        time: '20 min',
        category: 'Oferta',
      },
      {
        id: 'm3-7-piezas',
        text: 'Completar las 7 piezas de la oferta completa',
        detail: '1. Para quién es 2. El problema 3. El resultado 4. Cómo lo hacés (3-4 pasos) 5. Qué incluye 6. El precio 7. Objeciones resueltas',
        critical: true,
        time: '45 min',
        category: 'Oferta',
      },
      {
        id: 'm3-precio',
        text: 'Definir precio de lanzamiento y precio regular',
        detail: 'Precio de lanzamiento para primeros 2-3 clientes (que te incomode pero sea alcanzable). Precio regular para después. Basado en el valor que generás, no en lo que te sentís cómodo.',
        critical: true,
        time: '15 min',
        category: 'Pricing',
      },
      {
        id: 'm3-value-stack',
        text: 'Agregar 2-3 extras de valor alrededor del servicio principal',
        detail: 'Reporte mensual, acceso por WhatsApp, template, checklist, auditoría inicial, garantía. Cosas que cuestan poco a vos pero el cliente percibe como valioso.',
        time: '20 min',
        category: 'Oferta',
      },
      {
        id: 'm3-objeciones',
        text: 'Documentar las 3 objeciones principales y tu respuesta',
        detail: '"Es caro" / "No tengo tiempo" / "Ya intenté algo así". Escribí tu respuesta específica para cada una usando los números del cliente.',
        critical: true,
        time: '20 min',
        category: 'Oferta',
      },
      {
        id: 'm3-prueba-oral',
        text: 'Leer la oferta en voz alta y grabarte',
        detail: 'Imaginate que se la estás leyendo a tu cliente ideal. ¿Suena a algo que esa persona necesita escuchar? Si suena torpe o genérico, simplificá.',
        time: '10 min',
        category: 'Validación',
      },
      {
        id: 'm3-workbook',
        text: 'Completar el workbook "Mi Oferta Completa"',
        detail: 'Todas las 7 piezas escritas en el workbook. No en tu cabeza. En papel/digital.',
        time: '15 min',
        category: 'Workbook',
      },
    ],
  },

  // ─────────────────────────────────────────────
  // MÓDULO 4 — INCORPORACIÓN EN USA
  // ─────────────────────────────────────────────
  'modulo-4-incorporacion': {
    moduleSlug: 'modulo-4-incorporacion',
    title: 'Checklist — Módulo 4',
    description: 'Este módulo es el más técnico pero también el más concreto. Al terminar tenés infraestructura legal y financiera real.',
    completionMessage: '¡Empresa operacional en USA! Podés facturar en dólares a clientes americanos de forma legal. Eso es un hito enorme.',
    nextAction: 'Empezar Módulo 5: Consigue Tus Primeros Clientes',
    items: [
      {
        id: 'm4-ver-lecciones',
        text: 'Ver las 6 lecciones del Módulo 4',
        detail: 'LLC vs Corp, formar LLC con Doola, EIN, cuenta bancaria, Stripe, mover dinero',
        critical: true,
        time: '~2 horas',
        category: 'Lecciones',
      },
      {
        id: 'm4-nombre-empresa',
        text: 'Elegir el nombre de tu empresa',
        detail: 'Que se pueda pronunciar en inglés, que sea profesional y claro. No te tomes más de 30 minutos — podés cambiarlo después.',
        critical: true,
        time: '30 min',
        category: 'LLC',
      },
      {
        id: 'm4-recibo',
        text: 'Conseguir recibo público a tu nombre (agua, luz, teléfono)',
        detail: 'CRÍTICO: Sin esto, el banco puede rechazarte. El recibo debe tener tu nombre y tu dirección actuales.',
        critical: true,
        time: 'Variable',
        category: 'LLC',
      },
      {
        id: 'm4-doola',
        text: 'Crear cuenta en Doola y completar formulario de LLC',
        detail: 'doola.com → Start a U.S. Company → LLC → Florida → completar con datos exactos del pasaporte. Usar código REFERAFOUNDER10 para 10% off.',
        critical: true,
        tool: 'Doola',
        time: '20 min',
        category: 'LLC',
      },
      {
        id: 'm4-pagar-doola',
        text: 'Pagar la formación de LLC ($300-500)',
        detail: 'Una vez que pagás, Doola empieza el proceso. Los documentos llegan en 7-14 días hábiles.',
        critical: true,
        time: '5 min',
        category: 'LLC',
      },
      {
        id: 'm4-esperar-docs',
        text: 'Esperar y recibir los 4 documentos de Doola',
        detail: 'Articles of Organization + EIN (carta del IRS) + Operating Agreement + Dirección registrada. Los recibirás por email.',
        critical: true,
        time: '7-14 días',
        category: 'LLC',
      },
      {
        id: 'm4-presencia-online',
        text: 'Crear presencia online básica antes de aplicar al banco',
        detail: 'Perfil de LinkedIn con el nombre de la empresa, o página simple en Carrd/Notion, o Instagram de negocio. Los bancos te googlearán.',
        critical: true,
        tool: 'LinkedIn o Carrd',
        time: '30-60 min',
        category: 'Banco',
      },
      {
        id: 'm4-mercury',
        text: 'Aplicar a Mercury con todos los documentos',
        detail: 'mercury.com → cuenta business → subir Articles of Organization, EIN, pasaporte. Nombre exacto de LLC. Descripción específica del negocio en inglés.',
        critical: true,
        tool: 'Mercury',
        time: '20 min',
        category: 'Banco',
      },
      {
        id: 'm4-banco-aprobado',
        text: 'Confirmación de banco aprobado (Mercury o Relay)',
        detail: 'Si Mercury rechaza, aplicar inmediatamente a Relay. Si Relay también rechaza, revisar documentos y causas antes de reintentar.',
        critical: true,
        time: '1-5 días',
        category: 'Banco',
      },
      {
        id: 'm4-wise',
        text: 'Crear cuenta en Wise y conectar banco americano',
        detail: 'wise.com → cuenta business → conectar Mercury/Relay como fuente → agregar banco local como destino.',
        critical: true,
        tool: 'Wise',
        time: '20 min',
        category: 'Dinero',
      },
      {
        id: 'm4-stripe',
        text: 'Crear y configurar cuenta de Stripe',
        detail: 'stripe.com → cuenta business → EIN → nombre exacto de LLC → conectar Mercury → subir pasaporte. Esperar aprobación (24-48 horas).',
        critical: true,
        tool: 'Stripe',
        time: '20 min',
        category: 'Pagos',
      },
      {
        id: 'm4-stripe-test',
        text: 'Hacer pago de prueba de $1 en Stripe',
        detail: 'Crear un Payment Link en Stripe, pagarlo con tu propia tarjeta, confirmar que el dinero llega a Mercury. Solo cuando lo ves en la cuenta, el sistema está funcionando.',
        critical: true,
        time: '10 min',
        category: 'Pagos',
      },
      {
        id: 'm4-salario',
        text: 'Definir tu salario mensual y fecha de pago',
        detail: 'Decidir cuánto te pagás a vos mismo cada mes (en USD) y en qué fecha(s). Ej: $800 el 1 y el 15. Tratalo como una nómina real.',
        time: '10 min',
        category: 'Dinero',
      },
      {
        id: 'm4-contador',
        text: 'Agendar consulta con contador sobre obligaciones fiscales',
        detail: 'No lo dejes para después. Una consulta de 30 minutos con alguien que entienda LLC + ingresos del exterior puede ahorrarte miles en problemas futuros.',
        time: 'Variable',
        category: 'Legal/Fiscal',
      },
    ],
  },

  // ─────────────────────────────────────────────
  // MÓDULO 5 — PRIMEROS CLIENTES
  // ─────────────────────────────────────────────
  'modulo-5-clientes': {
    moduleSlug: 'modulo-5-clientes',
    title: 'Checklist — Módulo 5',
    description: 'El módulo más importante. Al completar esto tenés un sistema funcionando que genera llamadas con prospectos cada semana.',
    completionMessage: '¡Sistema de adquisición activo! Tenés cold email corriendo, LinkedIn complementando, y el script de llamadas listo. A partir de ahora es un juego de volumen y consistencia.',
    nextAction: 'Ejecutar: mandar 500 emails esta semana',
    items: [
      {
        id: 'm5-ver-lecciones',
        text: 'Ver las 10 lecciones del Módulo 5',
        detail: 'Cold email intro, setup Instantly, lista de prospectos, scripts de email, lanzar campaña, follow-ups, LinkedIn, primera llamada, cierre, manejo de ghosteo',
        critical: true,
        time: '~4 horas',
        category: 'Lecciones',
      },
      {
        id: 'm5-instantly',
        text: 'Crear cuenta en Instantly.ai',
        detail: 'instantly.ai → crear cuenta → elegir plan básico',
        critical: true,
        tool: 'Instantly',
        time: '10 min',
        category: 'Infraestructura',
      },
      {
        id: 'm5-dominios',
        text: 'Comprar 3-5 dominios secundarios en Instantly',
        detail: 'Variaciones de tu dominio principal (ej: getfreedomai.com). Nunca usar el dominio principal para cold email.',
        critical: true,
        tool: 'Instantly',
        time: '20 min',
        category: 'Infraestructura',
      },
      {
        id: 'm5-emails',
        text: 'Crear 1-2 cuentas de email por dominio con nombres reales',
        detail: 'jose@getfreedomai.com — nunca info@, sales@, contact@. Nombres reales de personas, no cargos.',
        critical: true,
        tool: 'Instantly',
        time: '20 min',
        category: 'Infraestructura',
      },
      {
        id: 'm5-auth',
        text: 'Verificar SPF, DKIM y DMARC en verde para todos los dominios',
        detail: 'En Instantly, cada dominio debe mostrar los 3 registros de autenticación en VERDE. Si alguno está en rojo, no sigas.',
        critical: true,
        tool: 'Instantly',
        time: '10 min',
        category: 'Infraestructura',
      },
      {
        id: 'm5-warmup',
        text: 'Activar warmup en todas las cuentas de email',
        detail: 'Iniciar con 10-20 emails/día por cuenta. Dejar correr MÍNIMO 2 semanas antes de lanzar campañas reales.',
        critical: true,
        tool: 'Instantly',
        time: '15 min',
        category: 'Infraestructura',
      },
      {
        id: 'm5-apollo',
        text: 'Crear cuenta en Apollo.io y configurar filtros de búsqueda',
        detail: 'Usar tu Ficha de Cliente Ideal para los filtros: título (Owner/Founder), industria, ubicación en USA, tamaño (1-50 empleados)',
        critical: true,
        tool: 'Apollo',
        time: '20 min',
        category: 'Lista de prospectos',
      },
      {
        id: 'm5-exportar',
        text: 'Exportar primer batch de 2,500 contactos en CSV',
        detail: 'Revisar que los resultados se vean correctos antes de exportar. Calidad > cantidad.',
        critical: true,
        tool: 'Apollo',
        time: '20 min',
        category: 'Lista de prospectos',
      },
      {
        id: 'm5-verificar',
        text: 'Verificar emails con MillionVerifier — eliminar inválidos',
        detail: 'Subir CSV a MillionVerifier, quedarse solo con "Good" o "Valid". Eliminar todos los demás.',
        critical: true,
        tool: 'MillionVerifier',
        time: '30 min',
        category: 'Lista de prospectos',
      },
      {
        id: 'm5-batches',
        text: 'Dividir lista verificada en batches de 500-600',
        detail: 'Nombrar claramente: "Restaurantes Miami - Batch 1", "Restaurantes Houston - Batch 1". Nunca una lista sola de 2,500.',
        time: '10 min',
        category: 'Lista de prospectos',
      },
      {
        id: 'm5-email-principal',
        text: 'Escribir el email principal usando uno de los dos frameworks',
        detail: 'Framework de Observación o Framework Directo. Máximo 100 palabras. Sin negritas ni HTML. Texto plano. Leerlo en voz alta.',
        critical: true,
        time: '30 min',
        category: 'Scripts',
      },
      {
        id: 'm5-asuntos',
        text: 'Escribir 3 variaciones de asunto para probar',
        detail: 'Cortos, específicos, que suenen a persona. Ej: "pregunta rápida" / "idea para {{companyName}}" / "algo que noté sobre tu restaurante"',
        critical: true,
        time: '15 min',
        category: 'Scripts',
      },
      {
        id: 'm5-followups',
        text: 'Escribir los 3 follow-ups (días 3, 6 y 9)',
        detail: 'Follow-up 1: recordatorio corto. Follow-up 2: ángulo nuevo con dato. Follow-up 3: breakup respetuoso.',
        critical: true,
        time: '30 min',
        category: 'Scripts',
      },
      {
        id: 'm5-campana',
        text: 'Crear primera campaña en Instantly con límites conservadores',
        detail: 'Subir Batch 1, configurar envío en horario laboral USA (8am-12pm EST), empezar con 20-30 emails/día total.',
        critical: true,
        tool: 'Instantly',
        time: '20 min',
        category: 'Campaña',
      },
      {
        id: 'm5-test-send',
        text: 'Hacer test send y verificar que todo se ve correcto',
        detail: 'Mandarte el email a vos mismo. Verificar que las variables ({{firstName}}, {{companyName}}) se reemplazan correctamente.',
        critical: true,
        time: '5 min',
        category: 'Campaña',
      },
      {
        id: 'm5-lanzar',
        text: 'Lanzar la primera campaña',
        detail: '¡El momento de la verdad! Una vez lanzada, revisar métricas una vez al día. No más.',
        critical: true,
        time: '5 min',
        category: 'Campaña',
      },
      {
        id: 'm5-linkedin-perfil',
        text: 'Optimizar perfil de LinkedIn',
        detail: 'Foto profesional + headline con tu frase de oferta + sección About con los 4 párrafos. Una vez y te sirve para siempre.',
        critical: true,
        tool: 'LinkedIn',
        time: '45 min',
        category: 'LinkedIn',
      },
      {
        id: 'm5-linkedin-diario',
        text: 'Empezar rutina diaria de LinkedIn (15-20 min/día)',
        detail: '10-15 conexiones de prospectos + 3-5 comentarios con sustancia en contenido del nicho. Todos los días.',
        time: '15-20 min/día',
        category: 'LinkedIn',
      },
      {
        id: 'm5-calendly',
        text: 'Configurar Calendly para agendar llamadas',
        detail: 'calendly.com → link de 30 minutos → disponibilidad en horario USA. Este link es el que mandás cuando alguien responde.',
        critical: true,
        tool: 'Calendly',
        time: '20 min',
        category: 'Ventas',
      },
      {
        id: 'm5-script-llamada',
        text: 'Preparar el script de llamada de ventas',
        detail: 'Preguntas de descubrimiento escritas en papel (dolor, deseo, urgencia). Oferta completa abierta en pantalla. Link de Stripe listo para mandar.',
        critical: true,
        time: '30 min',
        category: 'Ventas',
      },
      {
        id: 'm5-primera-llamada',
        text: 'Hacer la primera llamada de ventas (aunque sea imperfecta)',
        detail: 'Cuando llegue la primera respuesta positiva: agendar INMEDIATAMENTE. No esperar. No "primero me preparo más". Agendar y hacer.',
        critical: true,
        time: '30-45 min',
        category: 'Ventas',
      },
    ],
  },
}
